OrangeBricks.Web/Models/Offer.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace OrangeBricks.Web.Models
{
    public class Offer
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string BuyerUserId { get; set; }

        [Required]
        public int Amount { get; set; }

        [Required]
        public OfferStatus Status { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        [Required]
        public DateTime UpdatedAt { get; set; }
    }
}

OrangeBricks.Web/Controllers/Offers/OffersController.cs
using System.Web.Mvc;
using OrangeBricks.Web.Attributes;
using OrangeBricks.Web.Controllers.Offers.Builders;
using OrangeBricks.Web.Controllers.Offers.Commands;
using OrangeBricks.Web.Models;
using Microsoft.AspNet.Identity;

namespace OrangeBricks.Web.Controllers.Offers
{
    
    public class OffersController : Controller
    {
        private readonly IOrangeBricksContext _context;

        public OffersController(IOrangeBricksContext context)
        {
            _context = context;
        }

        public ActionResult OnProperty(int id)
        {
            var builder = new OffersOnPropertyViewModelBuilder(_context);
            var viewModel = builder.Build(id, this.User.Identity.GetUserId());

            return View(viewModel);
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult Accept(AcceptOfferCommand command)
        {
            var handler = new AcceptOfferCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("OnProperty", new { id = command.PropertyId });
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult Reject(RejectOfferCommand command)
        {
            var handler = new RejectOfferCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("OnProperty", new { id = command.PropertyId });
        }
    }
}

OrangeBricks.Web/Controllers/Property/PropertyController.cs
using System.Collections;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OrangeBricks.Web.Attributes;
using OrangeBricks.Web.Controllers.Property.Builders;
using OrangeBricks.Web.Controllers.Property.Commands;
using OrangeBricks.Web.Controllers.Property.ViewModels;
using OrangeBricks.Web.Models;

namespace OrangeBricks.Web.Controllers.Property
{
    public class PropertyController : Controller
    {
        private readonly IOrangeBricksContext _context;

        public PropertyController(IOrangeBricksContext context)
        {
            _context = context;
        }

        [Authorize]
        public ActionResult Index(PropertiesQuery query)
        {
            var builder = new PropertiesViewModelBuilder(_context);
            query.UserId = this.User.Identity.GetUserId();
            var viewModel = builder.Build(query);

            return View(viewModel);
        }

        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult Create()
        {
            var viewModel = new CreatePropertyViewModel();

            viewModel.PossiblePropertyTypes = new string[] { "House", "Flat", "Bungalow" }
                .Select(x => new SelectListItem { Value = x, Text = x })
                .AsEnumerable();

            return View(viewModel);
        }

        [OrangeBricksAuthorize(Roles = "Seller")]
        [HttpPost]
        public ActionResult Create(CreatePropertyCommand command)
        {
            var handler = new CreatePropertyCommandHandler(_context);

            command.SellerUserId = User.Identity.GetUserId();

            handler.Handle(command);

            return RedirectToAction("MyProperties");
        }

        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult MyProperties()
        {
            var builder = new MyPropertiesViewModelBuilder(_context);
            var viewModel = builder.Build(User.Identity.GetUserId());

            return View(viewModel);
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult ListForSale(ListPropertyCommand command)
        {
            var handler = new ListPropertyCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("MyProperties");
        }

        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult MakeOffer(int id)
        {
            var builder = new MakeOfferViewModelBuilder(_context);
            var viewModel = builder.Build(id);
            return View(viewModel);
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult MakeOffer(MakeOfferCommand command)
        {
            var handler = new MakeOfferCommandHandler(_context);

            command.BuyerUserId = this.User.Identity.GetUserId();
            handler.Handle(command);

            return RedirectToAction("OnProperty", "Offers", new { id = command.PropertyId });
        }

        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult ScheduleViewing(int id)
        {
            var builder = new ScheduleViewingViewModelBuilder(_context);
            var viewModel = builder.Build(id);
            return View(viewModel);
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult ScheduleViewing(ScheduleViewingCommand command)
        {
            var handler = new ScheduleViewingCommandHandler(_context);

            command.BuyerUserId = this.User.Identity.GetUserId();
            handler.Handle(command);

            return RedirectToAction("OnProperty", "Viewings", new { id = command.PropertyId });
        }
    }
}

OrangeBricks.Web/Views/Offers/OnProperty.cshtml
@model OrangeBricks.Web.Controllers.Offers.ViewModels.OffersOnPropertyViewModel

@{
    ViewBag.Title = "Offers for " + Model.StreetName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>Here you can see the offers that have been made on this property.</p>

<p><strong>Property type:</strong> @Model.PropertyType</p>
<p><strong>Number of bedrooms:</strong> @Model.NumberOfBedrooms</p>
<p><strong>Street name:</strong> @Model.StreetName</p>

@if (Model.HasOffers)
{
    <p>There are @Model.Offers.Count() offers on this property...</p>

    foreach (var offer in Model.Offers)
    {
        <hr />
        <div>
            <p><strong>Offer Amount: </strong> £@offer.Amount</p>
            <p><strong>Offer Made At: </strong> @offer.CreatedAt.ToLongTimeString() on @offer.CreatedAt.ToShortDateString()</p>
            <p><strong>Status: </strong> @offer.Status</p>
        </div>

        if (Model.UserIsSeller)
        {
            if (offer.IsPending)
            {
                using (Html.BeginForm("Accept", "Offers"))
                {
                    @Html.Hidden("PropertyId", Model.PropertyId)
                    @Html.Hidden("OfferId", offer.Id)
                    <p>
                        <input type="submit" class="btn btn-default" value="Accept Offer" />
                    </p>
                }
                using (Html.BeginForm("Reject", "Offers"))
                {
                    @Html.Hidden("PropertyId", Model.PropertyId)
                    @Html.Hidden("OfferId", offer.Id)
                    <p>
                        <input type="submit" class="btn btn-default" value="Reject Offer" />
                    </p>
                }
            }
        }
    }
}
else
{
    <div class="alert alert-info" role="alert">
        This property has no offers yet!
    </div>
}

@if (!Model.UserIsSeller)
{
    if (!Model.HasPendingOffers)
    {
        <a href="@Url.Action("MakeOffer", "Property", new { id = Model.PropertyId })" class="btn btn-primary">
            Make Offer
        </a>
    }
}